---
title: Title here

blinded: 0

authors: 
- name: Leonardo Uchoa Pedreira
  affiliation: "RA: 156231"
  
- name: Victor Freguglia Souza
  affiliation: "RA: 137784"

keywords:
- 3 to 6 keywords
- that do not appear in the title

abstract: |
  The text of your abstract.  200 or fewer words.

bibliography: bibliography.bib
header-includes:
- \usepackage[utf8]{inputenc}
output: rticles::asa_article
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
# Possivelmente ajustar as figuras aqui direto.
```

```{r load_pkgs}
library(tidyverse)
```

```{r load_mnist, cache = TRUE}
if (file.exists("mnist_train.csv")){
  MNIST <- read_csv("mnist_train.csv", col_names = FALSE)
} else if (file.exists("../mnist_train.csv")) {
  MNIST <- read_csv("../mnist_train.csv", col_names = FALSE)
} else {
  stop("Não achei o arquivo do arquivo :( Precisa colocar o arquivo que a gente usou pros labs 'mnist_train.csv' na pasta.")
}

names(MNIST)[1] <- "Y"
MNIST$Y <- as.factor(MNIST$Y)

set.seed(1)
idx_teste <- sample(1:nrow(MNIST), 55000, replace = FALSE)
treino <- MNIST[-idx_teste, ]
teste <- MNIST[idx_teste, ]
```


# Introdução

- História
 @schapire1990
- Como funciona?
- Pq funciona?
  
# Metodologia
  
  - Ideia

## AdaBoost

## Tree Boosting

- Gradient Boosting

@schapire1990 

[@elements]

# Dados

Conjunto de dados MNIST.

- Mostrar alguns números

# Aplicação

- Ajuste
- Comparar com Random Forest, nnet

# Discussão

- Não sei o que entra em discussão/conclusão?
  
# Conclusão